//! Generate a Pure Data control panel for an ISF shader: one GUI box per
//! input, wired to [vlfo/param], plus [vlfo/send] and a delayed re-send so
//! the defaults reach vlfo after the connection is up. The window is saved at
//! twice the content size so it opens right with Pd's "zoom new windows".

use crate::isf::{InputKind, Isf};

fn esc(s: &str) -> String {
    s.replace('\\', "").replace(';', "\\;").replace(',', "\\,").replace('$', "")
}

fn num(v: f32) -> String {
    if v == v.trunc() && v.abs() < 1e9 {
        format!("{}", v as i64)
    } else {
        format!("{v}")
    }
}

struct Patch {
    objs: Vec<String>,
    conns: Vec<(usize, usize, usize, usize)>,
}

impl Patch {
    fn add(&mut self, s: String) -> usize {
        self.objs.push(s);
        self.objs.len() - 1
    }
    fn conn(&mut self, a: usize, ao: usize, b: usize, bi: usize) {
        self.conns.push((a, ao, b, bi));
    }
    fn nbx(&mut self, x: i32, y: i32, w: u32, min: f32, max: f32, val: f32, label: &str) -> usize {
        self.add(format!(
            "#X obj {x} {y} nbx {w} 14 {} {} 0 1 empty empty {} 0 -8 0 10 -262144 -1 -1 {} 256",
            num(min), num(max), esc(label), num(val)
        ))
    }
    fn param(&mut self, x: i32, y: i32, name: &str) -> usize {
        self.add(format!("#X obj {x} {y} vlfo/param {}", esc(name)))
    }
}

pub fn generate(isf: &Isf, title: &str, port: u16) -> String {
    let mut p = Patch { objs: Vec::new(), conns: Vec::new() };
    p.add(format!("#X text 12 6 {} - control panel generated by: vlfo inputs --pd", esc(title)));
    let desc: String = isf.description.chars().take(60).collect();
    if !desc.is_empty() {
        p.add(format!("#X text 12 20 {}", esc(&desc)));
    }
    p.add(format!("#X obj 12 44 vlfo/send {port}"));
    let lb = p.add("#X obj 160 44 loadbang".into());
    let del = p.add("#X obj 240 44 del 1000".into());
    p.add("#X text 320 44 re-sends every value once the connection is up".into());
    p.conn(lb, 0, del, 0);

    let (cols, cellw, cellh, y0) = (3usize, 220i32, 70i32, 84i32);
    let inputs: Vec<_> = isf.inputs.iter().filter(|i| i.kind != InputKind::Image).collect();
    for (i, inp) in inputs.iter().enumerate() {
        let x = 12 + (i % cols) as i32 * cellw;
        let y = y0 + (i / cols) as i32 * cellh;
        let name = inp.name.as_str();
        match &inp.kind {
            InputKind::Float { default, min, max } => {
                let n = p.nbx(x, y, 6, *min, *max, *default, name);
                let pr = p.param(x, y + 24, name);
                p.conn(n, 0, pr, 0);
                p.conn(del, 0, n, 0);
            }
            InputKind::Long { default, min, max } => {
                let n = p.nbx(x, y, 6, *min as f32, *max as f32, *default as f32, name);
                let pr = p.param(x, y + 24, name);
                p.conn(n, 0, pr, 0);
                p.conn(del, 0, n, 0);
            }
            InputKind::Bool { default } => {
                let t = p.add(format!(
                    "#X obj {x} {y} tgl 15 1 empty empty {} 17 7 0 10 -262144 -1 -1 {} 1",
                    esc(name),
                    *default as i32
                ));
                let pr = p.param(x, y + 24, name);
                let m = p.add(format!("#X msg {} {y} {}", x + 150, *default as i32));
                p.conn(t, 0, pr, 0);
                p.conn(del, 0, m, 0);
                p.conn(m, 0, t, 0);
            }
            InputKind::Event => {
                let b = p.add(format!(
                    "#X obj {x} {y} bng 15 250 50 0 empty empty {} 17 7 0 10 -262144 -1 -1",
                    esc(name)
                ));
                let pr = p.param(x, y + 24, name);
                p.conn(b, 0, pr, 0);
            }
            InputKind::Color { default } => {
                let t = p.add(format!("#X obj {} {} t b b b b", x + 150, y + 24));
                let pack = p.add(format!("#X obj {x} {} pack f f f f", y + 24));
                let pr = p.param(x, y + 48, name);
                p.conn(pack, 0, pr, 0);
                p.conn(del, 0, t, 0);
                // created last-component-first so load-time init values fill the
                // pack's cold inlets before the hot one fires
                for (k, ch) in ["r", "g", "b", "a"].iter().enumerate().rev() {
                    let label = if k == 0 { format!("{name}.{ch}gba") } else { "empty".to_string() };
                    let n = p.nbx(x + k as i32 * 36, y, 3, 0.0, 1.0, default[k], &label);
                    p.conn(n, 0, pack, k);
                    p.conn(t, k, n, 0);
                }
            }
            InputKind::Point2D { default } => {
                let t = p.add(format!("#X obj {} {} t b b", x + 150, y + 24));
                let pack = p.add(format!("#X obj {x} {} pack f f", y + 24));
                let pr = p.param(x, y + 48, name);
                p.conn(pack, 0, pr, 0);
                p.conn(del, 0, t, 0);
                for (k, ch) in ["x", "y"].iter().enumerate().rev() {
                    let label = if k == 0 { format!("{name}.{ch}y") } else { "empty".to_string() };
                    let n = p.nbx(x + k as i32 * 60, y, 5, -10.0, 10.0, default[k], &label);
                    p.conn(n, 0, pack, k);
                    p.conn(t, k, n, 0);
                }
            }
            InputKind::Image => {}
        }
    }
    let images: Vec<_> = isf.image_inputs().map(|i| i.name.as_str()).collect();
    let rows = inputs.len().div_ceil(cols) as i32;
    let mut y_end = y0 + rows * cellh + 10;
    if !images.is_empty() {
        p.add(format!("#X text 12 {y_end} image inputs (not controllable here): {}", esc(&images.join(" "))));
        y_end += 20;
    }
    let (w, h) = ((12 + cols as i32 * cellw + 12) * 2, (y_end + 20) * 2);
    let mut out = format!("#N canvas 100 100 {w} {h} 10;\n");
    for o in &p.objs {
        out.push_str(o);
        out.push_str(";\n");
    }
    for (a, ao, b, bi) in &p.conns {
        out.push_str(&format!("#X connect {a} {ao} {b} {bi};\n"));
    }
    out
}
